version: '3.8'

services:
    mongodb:
        container_name: mongodb
        build:
            context: ./mongodb
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M

    mongo-express:
        container_name: mongo-express
        build:
            context: ./mongo-express
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongodb
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M

volumes:
    mongo-data:
        name: mongo-data
